### ISSUE TITLE
Swift-Version of C-Tuner crashing with macOS Mojave

### ISSUE THREAD

**Issue by laberning** [billthefarmer/ctuner#1]
Im currently trying to run the new Swift-Version of your awesome Tuner with MacOS 10.14.2 but it currently does not seem to be compatible.

I think the given code was compiled with Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1). I can get it to compile with Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) with a few minor code changes (I can create a pull request for those) with the given make file.

The generated binary can be run successfully, but if it is packaged as MacOS-App-Bundle it crashes (due to the dylib files that seem to be incompatible).

To debug further I would like to get the project to run as Xcode but its a bit hard to guess the original .xcodeproj settings. Do you have instructions on that (or maybe a working XCode Project definition)?

**Comment by billthefarmer** [comment]
I've posted an update to GitHub. I've just rebuilt it with Swift 4.2.1 on High Sierra 10.13.6, I had to change one symbol. The reason for the dylib failure is that because I couldn't find the right Framework files I cheated and built a do-nothing test app with Xcode and copied the Frameworks folder out of it to use with Make to build the app. I haven't tried importing it into Xcode.

**Comment by billthefarmer** [comment]
You are only the second person to show an interest in my Windows/OSX/Linux apps on here since I transferred them from Google Code, although I did get a chap who came up with the idea of the note filters on the Linux version. I get a lot of feedback on my android apps, probably because they are on [F-Droid](https://search.f-droid.org/?q=billthefarmer&lang=en).

Do you think it would be a good idea to backport the enhancements I have recently added to the [android version](https://github.com/billthefarmer/tuner), like musical staff, temperaments, transposition, etc?

**Comment by laberning** [comment]
I see you are porting stuff back already :-)
There might be only little feedback on this version so far because it is not easy to find via google or similar.

I've used it today to tune the reeds of an accordion and it works perfectly! The graphical display is really helpful when fine tuning the tremolo...

BTW: One thing was driving me bananas today under Mojave when I finally got the app working: When I started the binary via command line it worked without problems, when I started it via the app bundle the tuner did not detect any audio signal. Turns out that Apple added a new app security model that requires the app to ask for permission to use the microphone...

To do so we have to add a key to the plist-file:
```
<key>NSMicrophoneUsageDescription</key>
<string>This app requires microphone access to record the audio of your instrument.</string>
```

**Comment by billthefarmer** [comment]
OK, thank you. I have added that. I have updated the swift version to include most of the extras in the android version, I am currently writing the staff view. Tremolo or swing is the reason why I included the frequency error. I will make a web page for this and my audio tools to hopefully attract more interest.
