### ISSUE TITLE
Alternative naming conventions for custom temperaments

### ISSUE THREAD

**Issue by alignwaivers** [billthefarmer/ctuner#2]
Awesome software, have used for awhile and It's great!
new use case though, for trying to implement tuning for 41 EDO (for the [Kite Guitar](https://en.xen.wiki/w/The_Kite_Guitar))

Is there a way of assigning names to each note in a custom temperament file? or of at least removing the automatic way it seems to parse note names at the moment?

Thanks much

**Comment by billthefarmer** [comment]
Very interesting idea. I have only implemented custom temperaments on the android version, but it wouldn't be any good for this because the whole analysis and display part of the app is designed around 12 note octaves and standard music notation.
It would be possible to use the audio input and DSP part of this code and build a new analysis and display system. However 41 EDO appears to be just one of several alternate tuning systems.
