### ISSUE TITLE
request: temperament that is 12-note subset of 41edo

### ISSUE THREAD

**Issue by wolftune** [billthefarmer/ctuner#4]
Related to https://github.com/billthefarmer/ctuner/issues/2

I think the solution here is simple. A 12-note subset of larger temperaments is still useful when tuning string instruments. It works to tune each string by choosing a note that's included.

So, going with the Kite guitar proposal of D being the same as it is in 12edo 440Hz standard:

- D 0¢
- E♭ -12.2¢
- E +4.88¢
- F -7.32¢
- F♯ +9.76¢
- G -2.440¢
- A♭ -14.64¢
- A +2.44¢
- B♭ -9.76¢
- B +7.32¢
- C -4.88¢
- C♯ +12.2¢

Call it "subset of 41edo" probably

**Comment by billthefarmer** [comment]
This can be tested using the [android](https://github.com/billthefarmer/tuner) version which can load custom temperaments. Rearranging your list so that it starts with C:

| Note | Cents | Offset ((1200 + ¢) / 1200) | Equal | 41edo subset (Equal x Offset) | 
| --- | ---: | --- | --- | --- | 
C | -4.88 | 0.995933333333333 | 1 | 0.995933333333333
C♯ | +12.2 | 1.01016666666667 | 1.059463094 | 1.07023430212233
D | 0 | 1 | 1.122462048 | 1.122462048
E♭ | -12.2 | 0.989833333333333 | 1.189207115 | 1.17711684266417
E | +4.88 | 1.00406666666667 | 1.25992105 | 1.26504472893667
F | -7.32 | 0.9939 | 1.334839854 | 1.3266973308906
F♯ | +9.76 | 1.00813333333333 | 1.414213562 | 1.42571583230427
G | -2.44 | 0.997966666666667 | 1.498307077 | 1.49526051927677
A♭ | -14.64 | 0.9878 | 1.587401052 | 1.5680347591656
A | +2.44 | 1.00203333333333 | 1.681792831 | 1.68521247642303
B♭ | -9.76 | 0.991866666666667 | 1.781797436 | 1.76730548352053
B | +7.32 | 1.0061 | 1.887748625 | 1.8992638916125

Turn it into a property list file and load it into the android app and see if it works.
```
# Custom Temperaments
41edo: 0.995933333333333, 1.07023430212233, 1.122462048, 1.17711684266417, \
1.26504472893667, 1.3266973308906, 1.42571583230427, 1.49526051927677, \
1.5680347591656, 1.68521247642303, 1.76730548352053, 1.8992638916125
```
[41edo.ods](https://github.com/billthefarmer/ctuner/files/7798955/41edo.ods)

**Comment by billthefarmer** [comment]
Well that appeared to work. I'm not competent to check that the above is correct, It needs checking before I add it to these apps. Which version, if any, of my tuner apps do you use?

![Screenshot_20220102-113438 1](https://user-images.githubusercontent.com/3448386/147885077-33871feb-b0c8-4cad-95e8-b491bcbc83d4.png)

**Comment by wolftune** [comment]
I have 1.43 installed from F-Droid. I don't see where in the app to go to load custom temperaments though.

**Comment by billthefarmer** [comment]
It's in the [README](https://github.com/billthefarmer/tuner#custom-temperaments) and in the app help. Put a text file `Tuner/Custom.text` with the content from above, give the app Storage permission, and it will load the temperament.

**Comment by wolftune** [comment]
That worked in terms of the test and loading the temperament. I'm having trouble verifying that the numbers are right though.

I tried some synth generated tones, and I'm getting inconsistencies. The readout is saying some pitches are on, some are sharp, some flat. They're not all registering that in-tune 41edo notes are all equally in-tune.

Not sure what to do. Maybe not worth the hassle to troubleshoot further. It's hard to tell what's going on. I didn't get a bunch of specific sine-wave generated tones in Audacity or something. Maybe that would be worthwhile in order to test and calibrate tuners generally.

If this were to go ahead, the name would definitely need to be "41edo subset"  since it's not full 41edo. Also, it's confusing that it says "41edo C" since D was intended to match 12edo D, but it's still "C" instrument in that it's not transposing like a clarinet or something.

**Comment by wolftune** [comment]
Okay, I played with scale workshop, and that provided some insights. 440Hz is showing as perfectly in-tune A even though I was suggesting that D of 12edo be unchanged and A be +2.44¢ from 12edo standard.

Adjusting scale workshop so that D does in fact match the normal 12edo 440Hz-standard D:

[scale workshop](https://sevish.com/scaleworkshop/?name=41%20equal%20divisions%20of%202%2F1&data=29.26829268292683%0A58.53658536585366%0A87.8048780487805%0A117.07317073170732%0A146.34146341463415%0A175.609756097561%0A204.8780487804878%0A234.14634146341464%0A263.4146341463415%0A292.6829268292683%0A321.9512195121951%0A351.219512195122%0A380.4878048780488%0A409.7560975609756%0A439.0243902439025%0A468.2926829268293%0A497.5609756097561%0A526.829268292683%0A556.0975609756098%0A585.3658536585366%0A614.6341463414634%0A643.9024390243902%0A673.1707317073171%0A702.439024390244%0A731.7073170731708%0A760.9756097560976%0A790.2439024390244%0A819.5121951219512%0A848.7804878048781%0A878.048780487805%0A907.3170731707318%0A936.5853658536586%0A965.8536585365854%0A995.1219512195122%0A1024.3902439024391%0A1053.658536585366%0A1082.9268292682927%0A1112.1951219512196%0A1141.4634146341464%0A1170.7317073170732%0A1200.&freq=440.621&midi=69&vert=13&horiz=2&colors=&waveform=octaver&ampenv=organ)

This is getting somewhere.

It *should* show 0¢ when I play either the A or D or G of the 41edo.

What I see instead is that D shows +3.52¢ and A displays +2.44¢ and G shows +4.60¢

I did verify that the 41edo D shows correctly as perfectly in tune when I set the tuner to regular 12 equal temperament.

**Comment by billthefarmer** [comment]
As well as selecting the 41edo temperament, you also need to select the key of D in the settings. That's because the list you gave me is effectively a scale in D. If that still isn't correct then my spreadsheet must be wrong.

Looking at your link to the scale workshop, it looks as if you could pick 12 frequencies from the list to correspond to your 12 notes above and that would work as a custom temperament, all the app cares about are the ratios between the values.

The library function that the app uses to read the custom file ignored the 'subset' part of '41edo subset', which is why it didn't appear.

**Comment by wolftune** [comment]
Hmm, changing the Key does do something. But A is still listed as sharp by the same amount though other notes are changing.

I think I know what's going on. It's not set to allow A to be not 440 while set to 440Hz "standard". I don't want to have the idea of the "key" being D, that's not really the point. None of this has to come from D necessarily, it's just a point of matching to 12edo notes.

So, if I just stick to C as the reference, it's (incidentally, following the existing choices for which enharmonics to include):
 
- C 0¢
- C♯ +17.08¢
- D +4.88¢
- E♭ -7.32¢
- E +9.76¢
- F -2.440¢
- F♯ +14.64¢
- G +2.44¢
- A♭ -9.76¢
- A +7.32¢
- B♭ -4.88¢
- B +12.2¢

And then the thing is to just set A=440.621 if the user cares to make D match 12edo D. I'm thinking this will work, that A440 will still be in-tune A if the tuning reference isn't changed. In other words, somehow the tuner is using the difference from A to C to discover what C is. The assumption is that A=440 unless that is itself changed, regardless of what the "key" is.

Yes, I'm not sure exactly how it works in terms of setting the file based on the Hz from Scale Workshop, but that would seem feasible.

**Comment by billthefarmer** [comment]
If you get my spreadsheet, [41edo.ods](https://github.com/billthefarmer/ctuner/files/7798955/41edo.ods), you can plug in the values from above and create your own `Custom.txt`. The code that applies the temperament adjustment compares with A, as you said:
```java
                    // Octave note number
                    int n = (note - key + OCTAVE) % OCTAVE;
                    // A note number
                    int a = (A_OFFSET - key + OCTAVE) % OCTAVE;

                        // Temperament ratio
                    double temperRatio = temperaments[temper][n] /
                        temperaments[temper][a];
                    // Equal ratio
                    double equalRatio = temperaments[EQUAL][n] /
                        temperaments[EQUAL][a];

                    // Temperament adjustment
                    double temperAdjust = temperRatio / equalRatio;

                    // Reference note
                    nearest = reference *
                        Math.pow(2.0, Math.round(cf) / 12.0) * temperAdjust;
```
Rather than attempting to adjust the reference, you should be able to adjust the values to compensate, using the spreadsheet.

**Comment by wolftune** [comment]
> Rather than attempting to adjust the reference, you should be able to adjust the values to compensate, using the spreadsheet.

Not sure I follow this. Are you saying there's a way to make it recognize a different pitch for "A" than 440Hz without changing the tuning reference of "440"? I mean, that would be nice and appropriate in this case.

**Comment by billthefarmer** [comment]
You are correct, you need to adjust the reference. I have published a new version of the android app which has an extra digit in the reference setting. You will need to uninstall and reinstall the latest version, or clear the app data (Settings->Apps->Tuner->Storage->CLEAR DATA) before you upgrade as AFAICT, the system won't let an app try and update an integer preference to a float and crashes.

![Screenshot_20220109-121923 1](https://user-images.githubusercontent.com/3448386/148682522-fc8ff077-d3a1-4e87-a133-4a40379231e2.png)

**Comment by wolftune** [comment]
Okay, I reinstalled, cleared data, it works as an app, but the custom temperament isn't listed any more. The file is still there in the same place.

**Comment by billthefarmer** [comment]
It probably doesn't have Storage permission.

You are using the android app, but this is the issues for the Windows/macOS/linux versions. I originally assumed you were using one of those as you raised the issue here. I don't intend to add custom temperaments to these versions as it would have to be implemented differently for each one with a different place and format for the custom temperaments file and the existing code uses static arrays for the temperaments.

**Comment by wolftune** [comment]
Sorry, I didn't realize there was a separate Windows/macOS/linux project and issues set. I see now that there's https://github.com/billthefarmer/tuner please feel free to move this if that's a possibility.

Anyway, the Android version is what I have been testing, and I verified that it does have storage permissions. I recall adding those permissiong in the prior version and then it worked. Now, it just says that it has them, but it's not working. I tried turning it on and off. Hmm…

**Comment by wolftune** [comment]
FWIW, my current file:

```
# Custom Temperaments
41edo: 1.000000000, 1.07454278537127, 1.1270267269952, 1.1819529515985, \
1.27016840787333, 1.3321256796302, 1.4314669674564, 1.50135363472323, \
1.5744901901104, 1.6920517672691, 1.77455145976027, 1.90694073602083
```

And I tried uninstalling and clearing storage and downgrading to the prior version and even then I'm not getting it to work again. I restarted the device. Frustrating. Not sure you can do anything to help. Thanks so much for all you do anyway. Feeling stuck unfortunately.

**Comment by billthefarmer** [comment]
I've tested your file, it works fine and it's the same numbers as I get by plugging in your values from above. You must have done something, get someone else to check it. When I get stuck like that I get my partner to have a look and she spots it straight off.

![Screenshot_20220111-173002 1](https://user-images.githubusercontent.com/3448386/149120467-22709cb6-3f1e-4281-8485-fb3ceb88e23d.png)

![Screenshot_20220112-101200 1](https://user-images.githubusercontent.com/3448386/149120776-8af59e3b-8209-4fbb-8b20-e42ba2a2ea20.png)

**Comment by wolftune** [comment]
Well, I'll say this is fixed, and just I'll give up for now on my device. I'll be able to promote this option for others potentially at least. I'll see if I ever get my device to recognize the file again. No idea what changed.
